### ISSUE TITLE
mc eternal won't initialize and gas conduits has been identified as the potential causes

### ISSUE THREAD

**Issue by s0meb0dynew** [pupnewfster/GasConduits#8] opened 2020-06-19 21:33 UTC
#### Issue Description:
can't start up mce

#### Steps to reproduce:

1.start up mce

#### Versions (do not say latest):

- Gas Conduits: 1.12.2
- EnderIO: 1.6.4
- Mekanism: 1.7.10
- Minecraft:  1.12.2
- Forge: 14.23.5.2847

#### Your most recent log file where the issue was present: 

[file:///E:/Minecraft%20Launcher/Instances/MC%20Eternal/crash-reports/crash-2020-06-19_17.14.24-client.txt
[crash-2020-06-19_17.14.24-client.txt](https://github.com/pupnewfster/GasConduits/files/4806767/crash-2020-06-19_17.14.24-client.txt)
]

**Comment by pupnewfster** [comment] 2020-06-19 22:02
Duplicate of #7

**Closed as completed by pupnewfster** 2020-06-19 22:02 UTC
Labels: duplicate
